configs:
  - endpoint: http://localhost:8011/
    namespace: httpbin
    header_auth:
      Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      X-Api-Key: testAPI KEY
  - endpoint: http://ip-api.com/
    namespace: ip-api
    header_auth:
